### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "f72214b4e2904ee5afe476e02be2f879",
  "accountNumber": "1000000002",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/b61ef6ca14904d52add3f62fcfce6412